(define (block-sqrt x)
  (define (good_enough? guess)
    (< (abs (- (square guess x)) 0.001)))
  (define (improve guess)
	(average guess(/ x guess)))
 (define (sqrt-iter guess)
     (if (good-enough? guess)
 	  guess
	(sqrt-iter (improve guess))))
 (sqrt_iter 1.0))